{
  "formatVersion": "1.1",
  "component": {
    "group": "net.devgoodies",
    "module": "GInspector",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GInspector-2.0.0.jar",
          "url": "GInspector-2.0.0.jar",
          "size": 132686,
          "sha512": "c843140894b35ed5bc0c1b4f69c5dc0291bfffe69cea6a1eb5bc7fc3a69f280dc3fde39c28eba056100f453e6a89d1f0c2449a0fbeadd1146628eb72897b2a6a",
          "sha256": "0433d5d5cf1e8942d3cbb7e3ab3679a9c91313271334bc7763e591f29e1720e1",
          "sha1": "6b1a931ef0ccf9192299ffac2abd6ffae476a367",
          "md5": "f40c0dac836bb76bc781d5d401202d57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "GInspector-2.0.0.jar",
          "url": "GInspector-2.0.0.jar",
          "size": 132686,
          "sha512": "c843140894b35ed5bc0c1b4f69c5dc0291bfffe69cea6a1eb5bc7fc3a69f280dc3fde39c28eba056100f453e6a89d1f0c2449a0fbeadd1146628eb72897b2a6a",
          "sha256": "0433d5d5cf1e8942d3cbb7e3ab3679a9c91313271334bc7763e591f29e1720e1",
          "sha1": "6b1a931ef0ccf9192299ffac2abd6ffae476a367",
          "md5": "f40c0dac836bb76bc781d5d401202d57"
        }
      ]
    }
  ]
}
